resources:
- name: source-code
  type: git
  source:
    uri: ssh://git@git.int.bellmedia.ca:7999/bondum/registration-dummy-rest-api.git
    branch: master
    private_key: {{git-private-key}}

jobs:
  - name: Build project
    plan:
    - get: source-code
      trigger: true
    - task: run tests
      privileged: true
      file: source-code/ci/UnitTests.yml
    - task: package
      privileged: true
      file: source-code/ci/package.yml
    - task: show jar
      config:
        platform: linux
        inputs:
        - name: source-code
        - name: package-output
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: sh
          args:
          - -exc
          - |
            ls ./package-output
