resources:
- name: source-code
  type: git
  source:
    uri: ssh://git@git.int.bellmedia.ca:7999/bondum/registration-dummy-rest-api.git
    branch: master
    private_key: {{git-private-key}}

- name: docker-image-to-docker-register
  type: docker-image
  source:
    repository: 10.1.175.107:5000/admin
    tag: "latest"
    insecure_registries: ["10.1.175.107:5000"]
    username: admin
    password: admin
    ca_certs:
    - domain: 10.1.175.107:5000
      cert: {{docker-registry_cert}}
    client_certs:
    - domain: 10.1.175.107:5000
      cert: {{docker-registry_cert}}
      key: {{docker-registry_key}}


jobs:
  - name: Build project
    plan:
    - get: source-code
      trigger: true
    - task: package
      file: source-code/ci/package.yml
    - put: docker-image-to-docker-register
      params:
        build: package-output
