resources:
- name: source-code
  type: git
  source:
    uri: ssh://git@git.int.bellmedia.ca:7999/bondum/registration-dummy-rest-api.git
    branch: master
    private_key: {{git-private-key}}

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/ci/package.yml
