resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/aboussofara/MicroService.git
    branch: master

- name: docker-image-to-docker-register
  type: docker-image
  source:
    repository: bellmediatest/registry
    email: amine.boussofara@bellmedia.ca
    username: bellmediatest
    password: Bmanita_1899


jobs:
  - name: Build project
    plan:
    - get: source-code
      trigger: true
    - task: package
      file: source-code/ci/package.yml
    - put: docker-image-to-docker-register
      params:
        build: package-output
